name: Run Google Sheets Script Inline

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install gspread oauth2client

    - name: Create credentials.json
      run: |
        echo "${{ secrets.GSHEET_CREDENTIALS }}" | sed 's/\\n/\n/g' > credentials.json

    - name: Check credentials.json content
      run: cat credentials.json

    - name: Create main.py
      run: |
        echo "import gspread" > main.py
        echo "from oauth2client.service_account import ServiceAccountCredentials" >> main.py
        echo "" >> main.py
        echo "def get_inductance_from_sheet():" >> main.py
        echo "    scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']" >> main.py
        echo "    creds = ServiceAccountCredentials.from_json_keyfile_name('credentials.json', scope)" >> main.py
        echo "    client = gspread.authorize(creds)" >> main.py
        echo "    sheet = client.open_by_key('15nJVmEYntjmux4jE37VeP_5nWJTFk2t0zzMjGzCvAzk').get_worksheet(0)" >> main.py
        echo "    value = sheet.acell('D1016').value" >> main.py
        echo "    try:" >> main.py
        echo "        inductance = float(value) * 1e-6" >> main.py
        echo "    except:" >> main.py
        echo "        raise ValueError(f'Invalid value: {value}')" >> main.py
        echo "    return inductance" >> main.py
        echo "" >> main.py
        echo "if __name__ == '__main__':" >> main.py
        echo "    L = get_inductance_from_sheet()" >> main.py
        echo "    print(f'Inductance from D1016: {L:.9f} H')" >> main.py

    - name: Run main.py
      run: python main.py
